/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      typography: ({ theme }) => ({
        dark: {
          css: {
            '--tw-prose-body': theme('colors.gray[50]'),
            '--tw-prose-headings': theme('colors.gray[50]'),
            '--tw-prose-lead': theme('colors.gray[50]'),
            '--tw-prose-links': theme('colors.gray[50]'),
            '--tw-prose-bold': theme('colors.gray[50]'),
            '--tw-prose-counters': theme('colors.gray[50]'),
            '--tw-prose-bullets': theme('colors.gray[50]'),
            '--tw-prose-hr': theme('colors.gray[50]'),
            '--tw-prose-quotes': theme('colors.gray[50]'),
            '--tw-prose-quote-borders': theme('colors.gray[50]'),
            '--tw-prose-captions': theme('colors.gray[50]'),
            '--tw-prose-code': theme('colors.gray[50]'),
            '--tw-prose-pre-code': theme('colors.gray[50]'),
            '--tw-prose-pre-bg': theme('colors.gray[50]'),
            '--tw-prose-th-borders': theme('colors.gray[50]'),
            '--tw-prose-td-borders': theme('colors.gray[50]'),
            '--tw-prose-invert-body': theme('colors.gray[50]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.gray[50]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.gray[50]'),
            '--tw-prose-invert-bullets': theme('colors.gray[50]'),
            '--tw-prose-invert-hr': theme('colors.gray[50]'),
            '--tw-prose-invert-quotes': theme('colors.gray[50]'),
            '--tw-prose-invert-quote-borders': theme('colors.gray[50]'),
            '--tw-prose-invert-captions': theme('colors.gray[50]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.gray[50]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.gray[50]'),
            '--tw-prose-invert-td-borders': theme('colors.gray[50]'),
          },
        },
        light: {
          css: {
            '--tw-prose-body': theme('colors.gray[800]'),
            '--tw-prose-headings': theme('colors.gray[800]'),
            '--tw-prose-lead': theme('colors.gray[800]'),
            '--tw-prose-links': theme('colors.gray[800]'),
            '--tw-prose-bold': theme('colors.gray[800]'),
            '--tw-prose-counters': theme('colors.gray[800]'),
            '--tw-prose-bullets': theme('colors.gray[800]'),
            '--tw-prose-hr': theme('colors.gray[800]'),
            '--tw-prose-quotes': theme('colors.gray[800]'),
            '--tw-prose-quote-borders': theme('colors.gray[800]'),
            '--tw-prose-captions': theme('colors.gray[800]'),
            '--tw-prose-code': theme('colors.gray[800]'),
            '--tw-prose-pre-code': theme('colors.gray[800]'),
            '--tw-prose-pre-bg': theme('colors.gray[800]'),
            '--tw-prose-th-borders': theme('colors.gray[800]'),
            '--tw-prose-td-borders': theme('colors.gray[800]'),
            '--tw-prose-invert-body': theme('colors.gray[800]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.gray[800]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.gray[800]'),
            '--tw-prose-invert-bullets': theme('colors.gray[800]'),
            '--tw-prose-invert-hr': theme('colors.gray[800]'),
            '--tw-prose-invert-quotes': theme('colors.gray[800]'),
            '--tw-prose-invert-quote-borders': theme('colors.gray[800]'),
            '--tw-prose-invert-captions': theme('colors.gray[800]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.gray[800]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.gray[800]'),
            '--tw-prose-invert-td-borders': theme('colors.gray[800]'),
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/line-clamp")],
};
